import React, { useEffect, useState } from "react";
import { Calendar, Mail, ShoppingBag, UserRound } from "lucide-react";
import { apiRequest } from "../../utils/api";
import { toPersianDigits } from "../../utils/formatters";
interface UserItem { id: number; email?: string; username?: string; firstName?: string; lastName?: string; createdAt: string | number; _count: { orders: number }; }
export const UsersTab: React.FC<{ token: string }> = ({ token }) => {
  const [users,setUsers]=useState<UserItem[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ void (async()=>{ setLoading(true); const r=await apiRequest<{users:UserItem[]}>("/api/admin/users",{token}); if(r.success&&r.data)setUsers(r.data.users); setLoading(false); })(); },[token]);
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold tracking-[.14em] text-sky-400">مشتریان</p><h2 className="mt-1 text-xl font-black text-slate-100">حساب‌های فروشگاه</h2><p className="mt-1 text-[11px] text-slate-500">مشتریان ثبت‌نام‌شده و سابقه خرید آن‌ها</p></div><span className="rounded-lg bg-slate-800 px-3 py-2 text-[10px] font-bold text-slate-400">{toPersianDigits(users.length)} مشتری</span></div>
  {loading?<div className="py-24 text-center text-xs text-slate-500">در حال دریافت مشتریان...</div>:users.length===0?<div className="rounded-2xl border border-dashed border-slate-700 p-14 text-center text-xs text-slate-500">هنوز مشتری ثبت‌نام‌شده‌ای وجود ندارد.</div>:<div className="overflow-hidden rounded-2xl border border-slate-700/50 bg-slate-800/30"><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="border-b border-slate-700/50 bg-slate-800/60 text-slate-500"><tr><th className="p-4">مشتری</th><th className="p-4">ایمیل</th><th className="p-4">سفارش‌ها</th><th className="p-4">تاریخ عضویت</th></tr></thead><tbody className="divide-y divide-slate-700/40">{users.map(u=><tr key={u.id} className="hover:bg-slate-800/50"><td className="p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-500/10 text-sky-400"><UserRound className="h-4 w-4" /></span><div><strong className="block text-slate-100">{[u.firstName,u.lastName].filter(Boolean).join(" ")||"مشتری فروشگاه"}</strong><span className="text-[9px] text-slate-500">#{toPersianDigits(u.id)}</span></div></div></td><td className="p-4"><span dir="ltr" className="inline-flex items-center gap-1.5 text-slate-300"><Mail className="h-3.5 w-3.5 text-slate-500" />{u.email||"—"}</span></td><td className="p-4"><span className="inline-flex items-center gap-1.5 rounded-lg bg-slate-700/40 px-2.5 py-1.5 font-bold text-slate-200"><ShoppingBag className="h-3.5 w-3.5 text-sky-400" />{toPersianDigits(u._count.orders)}</span></td><td className="p-4 text-slate-500"><span className="inline-flex items-center gap-1.5"><Calendar className="h-3.5 w-3.5" />{new Date(Number(u.createdAt)).toLocaleDateString("fa-IR")}</span></td></tr>)}</tbody></table></div></div>}</div>;
};
