import React, { useEffect, useState } from "react";
import { Headphones, LockKeyhole, LogIn, LogOut, Package, Save, User, X } from "lucide-react";
import { apiRequest } from "../utils/api";
import { toPersianDigits } from "../utils/formatters";

export interface AccountInfo { provider: "web" | null; name: string; email?: string; avatarUrl?: string; }
interface Props {
  isOpen: boolean; onClose: () => void; account: AccountInfo | null; ordersCount: number; subscriptionsCount: number; webToken: string | null;
  onLogin: () => void; onLogout: () => void; onOpenOrders: () => void; onOpenSubscriptions: () => void; onOpenSupport: () => void;
  onProfileUpdated: (value: { firstName: string; lastName: string }) => void; onNotify: (message: string, type?: "success" | "info" | "error") => void;
}
export const AccountModal: React.FC<Props> = (p) => {
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const parts = p.account?.name?.split(" ") || []; setFirstName(parts[0] || ""); setLastName(parts.slice(1).join(" ")); }, [p.account?.name]);
  if (!p.isOpen) return null;
  const save = async () => { if (!p.webToken) return; setSaving(true); const res = await apiRequest<{ user: { firstName?: string; lastName?: string } }>("/api/web-auth/profile", { method: "PUT", token: p.webToken, body: JSON.stringify({ firstName, lastName }) }); setSaving(false); if (res.success) { p.onProfileUpdated({ firstName, lastName }); p.onNotify("پروفایل ذخیره شد."); } else p.onNotify(res.error || "خطا در ذخیره پروفایل", "error"); };
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4" onClick={p.onClose}><div className="w-full max-w-lg overflow-hidden rounded-t-3xl border border-slate-700/60 bg-slate-900 shadow-2xl sm:rounded-3xl" onClick={(e) => e.stopPropagation()}>
    <div className="flex items-center justify-between border-b border-slate-700/50 p-4"><div><p className="text-[10px] text-sky-400">حساب مشتری</p><h2 className="text-sm font-black text-slate-100">پروفایل و سفارش‌ها</h2></div><button onClick={p.onClose} className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-800 text-slate-400"><X className="h-4 w-4" /></button></div>
    {!p.account ? <div className="p-8 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-sky-500/10 text-sky-400"><User className="h-6 w-6" /></span><h3 className="mt-4 text-base font-black text-slate-100">وارد حساب فروشگاه شوید</h3><p className="mx-auto mt-2 max-w-xs text-xs leading-6 text-slate-500">برای مشاهده سفارش‌ها، تحویل محصولات و خرید سریع‌تر یک حساب بسازید.</p><button onClick={() => { p.onClose(); p.onLogin(); }} className="mx-auto mt-5 flex h-11 items-center gap-2 rounded-xl bg-sky-500 px-5 text-xs font-black text-white"><LogIn className="h-4 w-4" />ورود / ثبت‌نام</button></div> : <div className="space-y-5 p-5">
      <div className="flex items-center gap-3 rounded-2xl bg-slate-800/45 p-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 font-black text-slate-900">{p.account.name.slice(0,1)}</span><div className="min-w-0"><strong className="block truncate text-sm text-slate-100">{p.account.name}</strong><span dir="ltr" className="block truncate text-left text-[10px] text-slate-500">{p.account.email}</span></div></div>
      <div className="grid grid-cols-3 gap-2"><button onClick={() => { p.onClose(); p.onOpenOrders(); }} className="rounded-xl border border-slate-700/50 bg-slate-800/30 p-3 text-center"><Package className="mx-auto h-4 w-4 text-sky-400" /><b className="mt-1 block text-sm text-slate-100">{toPersianDigits(p.ordersCount)}</b><span className="text-[9px] text-slate-500">سفارش</span></button><button onClick={() => { p.onClose(); p.onOpenSubscriptions(); }} className="rounded-xl border border-slate-700/50 bg-slate-800/30 p-3 text-center"><LockKeyhole className="mx-auto h-4 w-4 text-emerald-400" /><b className="mt-1 block text-sm text-slate-100">{toPersianDigits(p.subscriptionsCount)}</b><span className="text-[9px] text-slate-500">محصول فعال</span></button><button onClick={() => { p.onClose(); p.onOpenSupport(); }} className="rounded-xl border border-slate-700/50 bg-slate-800/30 p-3 text-center"><Headphones className="mx-auto h-4 w-4 text-amber-400" /><b className="mt-1 block text-sm text-slate-100">۲۴/۷</b><span className="text-[9px] text-slate-500">پشتیبانی</span></button></div>
      <div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-[10px] text-slate-500">نام</span><input value={firstName} onChange={(e) => setFirstName(e.target.value)} className="h-10 w-full rounded-xl border border-slate-700 bg-slate-800 px-3 text-xs text-slate-100" /></label><label><span className="mb-1 block text-[10px] text-slate-500">نام خانوادگی</span><input value={lastName} onChange={(e) => setLastName(e.target.value)} className="h-10 w-full rounded-xl border border-slate-700 bg-slate-800 px-3 text-xs text-slate-100" /></label></div>
      <div className="flex justify-between"><button onClick={p.onLogout} className="flex h-10 items-center gap-2 rounded-xl px-3 text-[10px] font-bold text-rose-400 hover:bg-rose-500/10"><LogOut className="h-4 w-4" />خروج</button><button onClick={save} disabled={saving} className="flex h-10 items-center gap-2 rounded-xl bg-sky-500 px-4 text-[10px] font-black text-white"><Save className="h-4 w-4" />{saving ? "در حال ذخیره" : "ذخیره پروفایل"}</button></div>
    </div>}
  </div></div>;
};
